INSERT INTO cars(name,
                 price,
                 color,
                 mileage,
                 sold,
                 description,
                 create_date,
                 body_id,
                 engine_id,
                 transmission_id,
                 image_id,
                 user_id)
VALUES ('TOYOTA',
        1050,
        'BLACK',
        3000, false,
        'TEST',
        current_timestamp,
        2,
        2,
        2,
        1,
        1);

INSERT INTO cars(name,
                 price,
                 color,
                 mileage,
                 sold,
                 description,
                 create_date,
                 body_id,
                 engine_id,
                 transmission_id,
                 image_id,
                 user_id)
VALUES ('MAZDA',
        1050,
        'GREEN',
        3000,
        true,
        'TEST_2',
        current_timestamp,
        3,
        3,
        3,
        1,
        1);